# Generated by Django 3.2 on 2024-05-12 16:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20240209_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_path',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_partner_logo_path),
        ),
    ]
